[package]
name = "restaurant-review"
version = "0.1.0"
edition = "2021"

[lib]
name = "restaurant_review"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.2.1"
borsh-derive = "1.2.1"
solana-program = "1.18.25"
thiserror = "1.0.64"

[dev-dependencies]
solana-sdk = "1.18.25"
